- name: variables from task
  hosts: localhost
  vars: # variables from play-level
    course: "aws"
    trainer: "shiva"
    duration: "120hrs"
  tasks:
    - name: tasks from information
      vars: # variables from task level
        course: "Azure"
      ansible.builtin.debug:
         msg: "I we are learning {{course}} my trainer is {{ trainer}} course duration is {{duration]}."
    - name: information from task level
      ansible.builtin.debug:
           msg: "I we are learning {{course}} my trainer is {{ trainer}} course duration is {{duration]}."
