- name: variables
  hosts: localhost
  vars:
     course: "aws"
     trainer: "shiva"
     duration: "120hrs"
  tasks:
   - name: print the information
     vars:
        course: "DevOps"
     ansible.builtin.debug:
        msg: "Hi , we  are learning from {{ course}} from trainer {{trainer}} duration is {{duration}}."

   - name: print the information from play level
     ansible.builtin.debug:
        msg: "Hi , we  are learning from {{ course}} from trainer {{trainer}} duration is {{duration}}."