- name: variables from files
  hosts: localhost
  vars_files:
    - var-files.yaml
  tasks:
      - name: print the information from files
        ansible,builtin.debug:
           msg: "Hi, we are learning {{course}} from trainer {{trainer}} course duration {{duration}]."
