- name: Variables from files
  hosts: localhost
  tasks:
    - name: Variables override information
      ansible.builtin.debug:
         msg: "Hi, We are learning {{Course}} from trainer {{Trainer}} course duration is {{Duration}}."

