- name: variables from the prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: please enter username
      private: false
    - name: password
      prompt: please enter password
      private: true
  tasks:
    - name: variables print the prompt information
      ansible.builtin.debug:
         msg: "hi, We are learning username {{username}}, password {{password}}"