- name: variables from inventory files
  hosts: localhost
  tasks:
    - name: variables getting from inventory file
      ansible.builtin.debug:
         msg: "Hi, We are learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}} timing sre {{timings}}"