- name: conditions
  hosts: localhost
  become: yes
  tasks:
    - name: check user exit or not
      ansible.builtin.command: id expense
      ignore_errors: true

    - name: say hello
      ansible.builtin.debug:
         msg: "hello"