- name: enter number
  hosts: localhost
  vars_prompt:
    name: number
    prompt: Please enter number
    private: no
  tasks:
    - name: enter the number
      ansible.builtin.debug:
        msg: "given number is {{number}} less than 10"
      when: number | int < 10

    - name: greater than 10
      ansible.builtin.debug:
         msg: "given number is {{number}} greater than 10"
      when: number | int >=10