- name: filters
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
         msg: "{{course | default('Ansible')}}"

- name: upper case letters
  hosts: localhost
  vars:
    greetings: "Hello Good morning"
  tasks:
    - name: print the values in upper-case
      ansible.builtin.debug:
         msg: "{{greetings | upper }}"

- name: lower case letters
  hosts: localhost
  tasks:
    - name: print the value information in lower case
      vars:
        greetings: "Hello Hi"
      ansible.builtin.debug:
         msg: "{{ greetings | lower}}"

- name: unique numbers
  hosts: localhost
  vars:
    numbers:
      - 1
      - 2
      - 3
      - 4
      - 4
      - 5
      - 5
      - 6
  tasks:
    - name: Print the unique numbers
      ansible.builtin.debug:
         msg: "{{numbers | unique}}"

