- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: install the packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest

      loop:
        - nginx
        - mysql
        - postfix